name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Android:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Build
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./AzureBlobStorageSampleApp.Android/AzureBlobStorageSampleApp.Android.csproj /verbosity:normal /p:Configuration=Release
  
    Functions:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Build
        run: |                    
          dotnet build ./AzureBlobStorageSampleApp.Functions/AzureBlobStorageSampleApp.Functions.csproj -c Release

    UITests:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Build
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./AzureBlobStorageSampleApp.UITests/AzureBlobStorageSampleApp.UITests.csproj /verbosity:normal /p:Configuration=Release